nwnxee/unified

Plugins/Events/CMakeLists.txt
Plugins/Events/Events.cpp
Plugins/Events/Events.hpp
Plugins/Events/Events/FeatEvents.cpp
Plugins/Events/Events/FeatEvents.hpp
Plugins/Events/NWScript/nwnx_events.nss

Adds an event hook for feat usage.

NWNX_Events: Add OnUseFeat event

---

Plugins/Events/Documentation/README.md
Plugins/JVM/Documentation/README.md
Plugins/Metrics_InfluxDB/Documentation/README.md
Plugins/Optimizations/Documentation/README.md
Plugins/Profiler/Documentation/README.md
Plugins/Repair/Documentation/README.md
Plugins/Ruby/Documentation/README.md
Plugins/Tracking/Documentation/README.md

re-created the missing stubs.
Note these are not meant to be complete, just a starting point for plugin authors to flesh out information about their plugin.

missing documentation stubs from earlier.

---

NWNXLib/Hooking/FunctionHook.cpp
NWNXLib/Hooking/FunctionHook.hpp
NWNXLib/Platform/Assembly.cpp
NWNXLib/Platform/Assembly.hpp

Fixes #13. 
@mtijanic pls review when you get a moment

ASLR thunk fix

---

Scripts/buildnwnx.sh

Add a new argument, -d, to the build script. When specified, this argument will build in debug configuration.

Add a new argument, -d, to the build script.

---

Plugins/SQL/Targets/MySQL.cpp

Exactly what it says on the tin.

MySQL: Don't be an idiot and initialize members explicitly

---

Dockerfile.builder
Plugins/SQL/CMakeLists.txt

Added libraries and settings so the builder will add PostgreSQL to the SQL library

Updated for PostgeSQL build

---

Plugins/Item/CMakeLists.txt
Plugins/Item/Documentation/README.md
Plugins/Item/Item.cpp
Plugins/Item/Item.hpp
Plugins/Item/NWScript/nwnx_item.nss

Only two functions by now: SetWeight and SeGoldPieceValue. Both functions have been tested on my module.
There is already an Object plugin the functionality could be added to this plugin instead of a new one... But if in the future we add custom ItemProperties an do so, maybe it's better to have it separated. Anyway, as you wish.
Regards

New Item Plugin

---

Plugins/Item/Item.cpp
Plugins/Item/Item.hpp
Plugins/Item/NWScript/nwnx_item.nss

- Deleted function SetItemColor: can be done with SetItemAppearance 
- Added SetAddGoldPieceValue, GetAddGoldPieceValue, GetBaseGoldPieceValue
- Changed name of SetGoldPieceValue to SetBaseGoldPieceValue
- Changed indexes used by function SetItemAppearance to positive values
- Modified nwnx_item.nss to include all the previous changes 
- Added the following functions to the .nss:
```
// Set oItem's base value in gold pieces (Total cost = base_value +
// additional_value). Will not persist through saving.
// NOTE: Equivalent to SetGoldPieceValue NWNX2 function
void NWNX_Item_SetBaseGoldPieceValue(object oItem, int g);
// Set oItem's additional value in gold pieces (Total cost = base_value +
// additional_value). Will persist through saving.
void NWNX_Item_SetAddGoldPieceValue(object oItem, …
```

Item plugin modification

---

Plugins/Creature/Creature.cpp
Plugins/Creature/Creature.hpp
Plugins/Creature/NWScript/nwnx_creature.nss

```
// Sets the creature's racial type 
void NWNX_Creature_SetRacialType(object creature, int racialtype);
```

Added SetRacialType

---

Plugins/Creature/Creature.cpp
Plugins/Creature/Creature.hpp
Plugins/Creature/NWScript/nwnx_creature.nss

Added NWNX_Creature_GetClericDomain(), NWNX_Creature_SetClericDomain(), and related constants.

Added NWNX_Creature cleric domain functions and constants

---

.gitignore
NWNXLib/Log.cpp

.gitignore folder created by CLion (should be ignored)

Change default NWNX log level to Notice

---

Core/NWNXCore.cpp

Direct users to file crashes here instead of redmine. Leave the old handlers in place and daisy chain them, so we still produce the log and dump file.

Override crash handlers with NWNX ones

---

Plugins/Player/NWScript/nwnx_player.nss
Plugins/Player/Player.cpp
Plugins/Player/Player.hpp

Very low level API at this point, directly exposing the underlying structure, for full customizability.
I can add some utility functions that create the QBS structure from a few arguments..

player: Add {Get,Set}QuickBarSlot functions

---

Plugins/Weapon/Documentation/README.md
Plugins/Weapon/NWScript/nwnx_weapon.nss
Plugins/Weapon/Weapon.cpp
Plugins/Weapon/Weapon.hpp

Added the following funcions:
```C
// Set required creature size for weapon nBaseItem to be finessable
void NWNX_Weapon_SetWeaponFinesseSize(int nBaseItem, int nSize);
// Set weapon nBaseItem to be considered as unarmed for weapon finesse feat
void NWNX_Weapon_SetWeaponUnarmed(int nBaseItem);
// Set nFeat as weapon improved critical feat for nBaseItem
void NWNX_Weapon_SetWeaponImprovedCriticalFeat(int nBaseItem, int nFeat);
// Set nFeat as weapon specialization feat for nBaseItem
void NWNX_Weapon_SetWeaponSpecializationFeat(int nBaseItem, int nFeat);
```

Weapon plugin update

---

Plugins/Player/NWScript/nwnx_player_qbs.nss

Minor QoL improvements so you don't have to fill in the structure manually.

Utilty nwscript for QuickBarSlot use

---

Plugins/Tweaks/CMakeLists.txt
Plugins/Tweaks/Documentation/README.md
Plugins/Tweaks/Tweaks.cpp
Plugins/Tweaks/Tweaks.hpp
Plugins/Tweaks/Tweaks/HideClassesOnCharList.cpp
Plugins/Tweaks/Tweaks/HideClassesOnCharList.hpp

This just comes with one thing so far - HIDE_CLASSES_ON_CHAR_LIST, which hides classes on the character list (default to off).

Add NWNX_Tweaks

---

.gitattributes
Plugins/Mono/Documentation/README.md
Plugins/Mono/Mono.cpp
Plugins/Mono/Mono_Handlers.cpp

Plus a couple bug fixes and log tweaks.

Add support for StartingConditionals to C#

---

Plugins/Creature/Creature.cpp
Plugins/Creature/Creature.hpp
Plugins/Creature/NWScript/nwnx_creature.nss

That removes a specific spell from a creature's spellbook
by class.

Added ClearMemorisedKnownSpells() function

---

Plugins/Creature/NWScript/nwnx_creature.nss

Fix for SetSpecialAbility, missing argument index.

Fix for SetSpecialAbility, missing argument index.

---

Plugins/Creature/Creature.cpp
Plugins/Creature/Creature.hpp
Plugins/Creature/NWScript/nwnx_creature.nss
Plugins/Creature/NWScript/nwnx_creature_t.nss

Totally straightforward, requested in #116 .

creature: Add SetGold function

---

Plugins/Object/NWScript/nwnx_object.nss
Plugins/Object/NWScript/nwnx_object_t.nss
Plugins/Object/Object.cpp
Plugins/Object/Object.hpp

SetPortrait was disabled due to CC issues, so re-enabled. And the other was requested in #26 
Pretty straightforward, but has whitespace cleanup as well. Added unit test, too!

Object - SetDialogResref() and SetPortrait()

---

Plugins/Damage/CMakeLists.txt
Plugins/Damage/Damage.cpp
Plugins/Damage/Damage.hpp
Plugins/Damage/Documentation/README.md
Plugins/Damage/NWScript/nwnx_damage.nss

Ported from Baaleos nwnx2 damage plugin.

New damage plugin

---

Plugins/Player/Player.cpp

Fixes #113 and a few other issues.
There is already a forced walk flag on creatures that is set/cleared by the movement altering effects. Just set that directly, and take both the "ALWAYS_WALK" property and the effects into account when clearing it.

player: Change SetAlwaysWalk to use m_bForcedWalk

---

Plugins/Metrics_InfluxDB/Documentation/README.md

I was working with InfluxDB and noticed the docs were not right. Just a small docs correction.

Updated InfluxDB plugin variables docs

---

README.md

Remove rogue pipe to fix broken link

---

README.md

Readme changes due to some internal changes in OpenLOTR repo.

OpenLOTR changes in the readme

---

Plugins/Lua/Documentation/README.md

I tried to keep it short. Please let me know if anything is unclear.

Document docker config for Plugins/Lua

---

Docker/Full/Dockerfile

Clone official repository

---

Plugins/Util/CMakeLists.txt
Plugins/Util/Documentation/README.md
Plugins/Util/NWScript/nwnx_util.nss
Plugins/Util/NWScript/nwnx_util_t.nss
Plugins/Util/Util.cpp
Plugins/Util/Util.hpp

Need some dumping ground for these things, so a new plugin. Maybe NWNX_Misc would have been a better name?
For now just the things I actively need, and I don't want to maintain a separate fork..

new utility plugin with misc functions

---

Plugins/Damage/Documentation/README.md

It said to use NWNX_Weapon instead of NWNX_Damage.

Fix documentation error

---

Plugins/Events/CMakeLists.txt
Plugins/Events/Events.cpp
Plugins/Events/Events.hpp
Plugins/Events/Events/HealerKitEvents.cpp
Plugins/Events/Events/HealerKitEvents.hpp
Plugins/Events/NWScript/nwnx_events.nss

- Added the Healer's kit event. The event can be bypassed.
- Added the skip event function (a "copy" of @Liareth skip event code, hope you don't mind)

Healer's kit event

---

Plugins/Events/Events.cpp
Plugins/Events/Events.hpp

@BhaalM please review when you get a chance and try this change with your events

Fix event data

---

Plugins/Tracking/Targets/Activity.cpp

See #192 .  No need for vtable faffery, exoapp already exposes a way to cycle through all clients and get both their client OIDs and their nwsobject OIDs. Can detect DM-ness from CNWSCreatureStats.
GetFirstPC/GetNextPC is safe to do as this is in the main loop update and won't trigger in the middle of someone else's iteration (e.g. while a script is running).
Verified it shows both PC and DMs properly. Can't really imagine a case where the nwsobject is null, but it'll show as `(unknown)` then if it ever happens.

tracking: fix player iteration and player/dm split

---

Plugins/Weapon/Weapon.cpp
Plugins/Weapon/Weapon.hpp

Added Flurry of blows for monk weapons defined with NWNX_Weapon_SetWeaponIsMonkWeapon function.

Flurry of blows

---

Plugins/Player/NWScript/nwnx_player.nss
Plugins/Player/Player.cpp
Plugins/Player/Player.hpp

Straightforward implementation of #176 . This shows a VFX for a given player only, in their current area.

Player: Add ShowVisualEffect() function.

---

Plugins/Player/NWScript/nwnx_player.nss
Plugins/Player/Player.cpp
Plugins/Player/Player.hpp

Adds the following functions which let you change/start/stop the music of the given player only:
MusicBackgroundChangeDay()
MusicBackgroundChangeNight()
MusicBackgroundStart()
MusicBackgroundStop()
MusicBattleChange()
MusicBattleStart()
MusicBattleStop()

Player: various music functions

---

NWNXLib/Log.cpp

Log: Write Log to User Directory

---

Plugins/Player/NWScript/nwnx_player.nss
Plugins/Player/Player.cpp
Plugins/Player/Player.hpp

A function to toggle a placeable's usable flag for the given player only.

Player: add SetPlaceableUsable() function

---

Dockerfile
Plugins/Area/Area.cpp
Plugins/Area/Area.hpp
Plugins/Area/CMakeLists.txt
Plugins/Area/Documentation/README.md
Plugins/Area/NWScript/nwnx_area.nss

Adds the following functions:
GetNumberOfPlayersInArea()
GetLastEntered()
GetLastLeft()
GetPVPSetting()
SetPVPSetting()
GetAreaSpotModifier()
SetAreaSpotModifier()
GetAreaListenModifier()
SetAreaListenModifier()
GetNoRestingAllowed()
SetNoRestingAllowed()
GetWindPower()
SetWindPower()
GetWeatherChance()
SetWeatherChance()
GetFogClipDistance()
SetFogClipDistance()
GetShadowOpacity()
SetShadowOpacity()
GetDayNightCycle()
SetDayNightCycle()

New Plugin: Area

---

Plugins/Util/NWScript/nwnx_util.nss
Plugins/Util/NWScript/nwnx_util_t.nss
Plugins/Util/Util.cpp
Plugins/Util/Util.hpp

Implementation of #269
Adds GetCustomToken() to NWNX_Util.

Util: added GetCustomToken()

---

Plugins/Administration/Administration.cpp
Plugins/Administration/NWScript/nwnx_admin_t.nss
Plugins/Area/NWScript/nwnx_area_t.nss
Plugins/Feedback/NWScript/nwnx_feedback_t.nss
Plugins/Visibility/NWScript/nwnx_visibilit_t.nss

Adds unit tests for the following plugins: Administration, Feedback, Visibility and Area
Also fixes a nullptr crash in Administration.

Couple of plugin unit tests + Administration Fix

---

Plugins/SQL/Targets/SQLite.cpp

SQL: Minor SQLite Changes

---

Plugins/Chat/Chat.cpp

chat: fix recursive message skipping

---

Plugins/Area/NWScript/nwnx_area.nss
Plugins/Damage/NWScript/nwnx_damage.nss
Plugins/Profiler/NWScript/nwnx_profiler.nss
Scripts/packageNWScript.sh

Fixes #295 
Odd that my toolset didn't trip over the NWNX_Area one when I wrote its unit test, oh well.

NWScript Fixes

---

Plugins/Metrics_InfluxDB/Documentation/README.md

Included some tips on setting up InfuxDB for proper ingestion of data from NWNX Metrics plugin

Added docs for Metrics plugin

---

Core/NWNXCoreVM.cpp

Copy/paste, not even once, kids ;D

Fix NWNXCoreVM.cpp

---

Plugins/Player/NWScript/nwnx_player.nss
Plugins/Player/Player.cpp
Plugins/Player/Player.hpp

A function to override a player's rest duration, minimum duration is 10ms otherwise it crashes the server.

Player: Add SetRestDuration()

---

Plugins/Player/NWScript/nwnx_player_qbs.nss

This is for the quick bar slots where you can add your own custom chat/emote/command

Add quickbar commands nss

---

CHANGELOG.md
Plugins/Effect/Effect.cpp
Plugins/Effect/Effect.hpp
Plugins/Effect/NWScript/nwnx_effect.nss

Lets you get the effect creator in an EffectExpired script.

Effect: add GetEffectExpiredCreator()

---

CHANGELOG.md
Plugins/ItemProperty/CMakeLists.txt
Plugins/ItemProperty/Documentation/README.md
Plugins/ItemProperty/ItemProperty.cpp
Plugins/ItemProperty/ItemProperty.hpp
Plugins/ItemProperty/NWScript/nwnx_itemprop.nss
Plugins/ItemProperty/NWScript/nwnx_itemprop_t.nss

Just a utility pack/unpack like the effects, but most of the effect crap is irrelevant to IPs. Can still use the converter functions in nwnx_util to convert between the two if needed.
Finally fully implements #31

ItemProperty plugin

---

CHANGELOG.md
Plugins/Events/CMakeLists.txt
Plugins/Events/Documentation/README.md
Plugins/Events/Events.cpp
Plugins/Events/Events.hpp
Plugins/Events/Events/PolymorphEvents.cpp
Plugins/Events/Events/PolymorphEvents.hpp
Plugins/Events/NWScript/nwnx_events.nss

Polymorph events

---

CHANGELOG.md
Plugins/Administration/Administration.cpp
Plugins/Administration/Administration.hpp
Plugins/Administration/NWScript/nwnx_admin.nss

A function to remove the Temporary User Resource Data of a player.

Administration: add DeleteTURD()

---

CHANGELOG.md
NWNXLib/API/Constants/MiscRules.hpp
Plugins/Events/Events/DMActionEvents.cpp
Plugins/Events/NWScript/nwnx_events.nss

More DMActionEvents, some cool ones too.
Test / Example:
```
void main()
{
object oDM = OBJECT_SELF;
if (FindSubString(sEvent, "NWNX_ON_DM_SPAWN_OBJECT_") != -1)
{
object oArea = NWNX_Object_StringToObject(NWNX_Events_GetEventData("AREA"));
object oItem = NWNX_Object_StringToObject(NWNX_Events_GetEventData("OBJECT"));
string objectType = NWNX_Events_GetEventData("OBJECT_TYPE");
string x = NWNX_Events_GetEventData("POS_X");
string y = NWNX_Events_GetEventData("POS_Y");
string z = NWNX_Events_GetEventData("POS_Z");
SendMessageToPC(oDM, (bBefore ? "BEFORE: " : "AFTER: ") + GetName(oDM) + " spawned object '" +
GetName(oItem) + "' of type '" + …
```

Events: Add SpawnObject/GiveItem/GiveAlignment Events to DMActionEvents

---

CHANGELOG.md
Plugins/Events/Events/DMActionEvents.cpp
Plugins/Events/Events/DMActionEvents.hpp
Plugins/Events/NWScript/nwnx_events.nss

You can skip pretty much all DMActionEvents now, I'll add the missing ones to the nwscript file one day, for now you can look in the source :D

Events: Make DMActionEvents Skippable

---

NWNXLib/Services/PerObjectStorage/PerObjectStorage.cpp

pos: Fix crash with bad turdlist

---

CHANGELOG.md
Plugins/Events/Events/DMActionEvents.cpp
Plugins/Events/Events/DMActionEvents.hpp
Plugins/Events/NWScript/nwnx_events.nss

Adds event data support for the following events:
```
NWNX_ON_DM_GOTO_BEFORE
NWNX_ON_DM_GOTO_AFTER
NWNX_ON_DM_POSSESS_BEFORE
NWNX_ON_DM_POSSESS_AFTER
NWNX_ON_DM_POSSESS_FULL_POWER_BEFORE
NWNX_ON_DM_POSSESS_FULL_POWER_AFTER
NWNX_ON_DM_TOGGLE_LOCK_BEFORE
NWNX_ON_DM_TOGGLE_LOCK_AFTER
NWNX_ON_DM_DISABLE_TRAP_BEFORE
NWNX_ON_DM_DISABLE_TRAP_AFTER
NWNX_ON_DM_JUMP_TO_POINT_BEFORE
NWNX_ON_DM_JUMP_TO_POINT_AFTER
NWNX_ON_DM_JUMP_TARGET_TO_POINT_BEFORE
NWNX_ON_DM_JUMP_TARGET_TO_POINT_AFTER
NWNX_ON_DM_JUMP_ALL_PLAYERS_TO_POINT_BEFORE
NWNX_ON_DM_JUMP_ALL_PLAYERS_TO_POINT_AFTER
```
Test / Usage Example:
```
include "nwnx_events"
void main()
{
object oDM = OBJECT_SELF;
if …
```

Events: Add Event Data support for single target / teleport based DMActionEvents

---

Plugins/Redis/Config.cpp

Redis: Log PubSub NWScript on load

---

CHANGELOG.md
Plugins/Area/Area.cpp
Plugins/Area/Area.hpp
Plugins/Area/NWScript/nwnx_area.nss

Resolves #351 
Adds SetSunMoonColors() to NWNX_Area.
You'll need to re-enter the area to see the changes.

Area: add SetSunMoonColors()

---

CHANGELOG.md
Plugins/Creature/Creature.cpp
Plugins/Creature/Creature.hpp
Plugins/Creature/NWScript/nwnx_creature.nss

Resolves #353 
Adds {Get/Set}OriginalName() to NWNX_Creature.

Creature: add {Get/Set}OriginalName()

---

CHANGELOG.md
NWNXLib/Utils.hpp
Plugins/Events/CMakeLists.txt
Plugins/Events/Documentation/README.md
Plugins/Events/Events.cpp
Plugins/Events/Events.hpp
Plugins/Events/Events/DMActionEvents.cpp
Plugins/Events/Events/MapEvents.cpp
Plugins/Events/Events/PartyEvents.cpp
Plugins/Events/Events/QuickChatEvents.cpp
Plugins/Events/Events/QuickChatEvents.hpp
Plugins/Events/NWScript/nwnx_events.nss

Events: add QuickChatEvents

---

Plugins/Reveal/NWScript/nwnx_reveal.nss

NSS Correction.

---

CHANGELOG.md
Plugins/Creature/Creature.cpp
Plugins/Creature/Creature.hpp
Plugins/Creature/NWScript/nwnx_creature.nss
Plugins/Creature/NWScript/nwnx_creature_t.nss

Adds SetSpellResistance() to NWNX_Creature.

Creature: SetSpellResistance()

---

Plugins/Events/Events/DMActionEvents.cpp

Events: fix DMActionEvents event data param

---

CHANGELOG.md
Plugins/Player/NWScript/nwnx_player.nss
Plugins/Player/Player.cpp
Plugins/Player/Player.hpp

Lets players open any creature inventory, including ones of other players.
Related part of #365

Player: add OpenInventory()

---

CHANGELOG.md
Plugins/Events/Events/ItemEvents.cpp
Plugins/Events/Events/ItemEvents.hpp
Plugins/Events/NWScript/nwnx_events.nss

Resolves #388 
Adds the following skippable event:
```
NWNX_ON_ITEM_SCROLL_LEARN_BEFORE
NWNX_ON_ITEM_SCROLL_LEARN_AFTER
```

Events: add ScrollLearn event to ItemEvents

---

CHANGELOG.md
Plugins/Object/NWScript/nwnx_object.nss
Plugins/Object/NWScript/nwnx_object_t.nss
Plugins/Object/Object.cpp
Plugins/Object/Object.hpp

Usage:
```
int nImmunity = NWNX_Object_GetDamageImmunity(oTarget, DAMAGE_TYPE_PIERCING);
```

added GetDamageImmunity function to Object plugin

---

CHANGELOG.md
Plugins/Events/Events/ItemEvents.cpp
Plugins/Events/Events/ItemEvents.hpp
Plugins/Events/NWScript/nwnx_events.nss

Item: Run{Un}Equip

---

Plugins/Effect/Effect.cpp
Plugins/Effect/NWScript/nwnx_effect.nss
Plugins/Effect/NWScript/nwnx_effect_t.nss

Effect: push the effectID when packing/unpacking

---

Plugins/Profiler/Targets/ObjectAIUpdates.cpp

Profiler: temporarily disable AIUpdateItem in ObjectAIUpdates

---

CHANGELOG.md
Plugins/Util/NWScript/nwnx_util.nss
Plugins/Util/NWScript/nwnx_util_t.nss
Plugins/Util/Util.cpp
Plugins/Util/Util.hpp

Fun time figuring out the constants for ResRef type. The default type was added for convenience but maybe it should be ITEM, or maybe there just shouldn't be a default?

Util: IsValidResRef()

---

CHANGELOG.md
Plugins/Object/NWScript/nwnx_object.nss
Plugins/Object/Object.cpp
Plugins/Object/Object.hpp

Lets you add a deserialized object to an area or move existing objects between areas.

Object: add AddToArea()

---

CHANGELOG.md
Plugins/Util/NWScript/nwnx_util.nss
Plugins/Util/NWScript/nwnx_util_t.nss
Plugins/Util/Util.cpp
Plugins/Util/Util.hpp

As demanded by sherincall the overlord.
I've verified this compiles and think it should be fairly safe, but I haven't had a chance to test it.
It could also use a test in `Plugins/Util/NWScript/nwnx_util_t.nss`, but I don't know the test environment well enough to say what we could expect to be in the env.

WIP: add GetEnvironmentVariable to Utils

---

CHANGELOG.md
Plugins/Events/CMakeLists.txt
Plugins/Events/Events.cpp
Plugins/Events/Events.hpp
Plugins/Events/Events/ExamineEvents.cpp
Plugins/Events/Events/ExamineEvents.hpp
Plugins/Events/Events/TrapEvents.cpp
Plugins/Events/Events/TrapEvents.hpp
Plugins/Events/NWScript/nwnx_events.nss

As discussed in #34. Still need Trap Trigger to close. Includes adding the `SendServerToPlayerExamineGui_TrapData` to `Examine` events.

Events: Traps

---

CHANGELOG.md
Plugins/Object/NWScript/nwnx_object.nss
Plugins/Object/NWScript/nwnx_object_t.nss
Plugins/Object/Object.cpp
Plugins/Object/Object.hpp

Resolves #418 - Considered adding another optional argument to change the Useable flag at the same time, but decided to just leave that to `SetUseableFlag`

Object: {Get|Set}PlaceableIsStatic

---

CHANGELOG.md
Plugins/Events/Events/ClientEvents.cpp
Plugins/Events/Events/ClientEvents.hpp
Plugins/Events/NWScript/nwnx_events.nss

Resolves #442 
Note if you choose to skip the event every time and validate through your own means the `knownservernames.2da` should never get created.
Example handler for a SQL validator:
```c
#include "nwnx_sql"
void main()
{
object oModule = OBJECT_SELF;
if (sCurrentEvent == "NWNX_ON_CHECK_STICKY_PLAYER_NAME_RESERVED_BEFORE")
{
string sPlayerName = NWNX_Events_GetEventData("PLAYER_NAME");
string sCDKey = NWNX_Events_GetEventData("CDKEY");
int isDM = StringToInt(NWNX_Events_GetEventData("IS_DM"));
string sSQL = "SELECT cdkey, can_dm FROM player_keys WHERE player_name = ?";
NWNX_SQL_PrepareQuery(sSQL);
NWNX_SQL_PreparedString(0, sPlayerName);
NWNX_SQL_ExecutePreparedQuery();
int iPlayerFound = 0;
while …
```

Events: CheckStickyPlayerNameReserved

---

CHANGELOG.md
Plugins/Object/Object.cpp
Plugins/Object/Object.hpp

Object: Allow GetLocalVariable{Count} on Module

---

CHANGELOG.md
Plugins/Object/NWScript/nwnx_object.nss
Plugins/Object/NWScript/nwnx_object_t.nss
Plugins/Object/Object.cpp
Plugins/Object/Object.hpp

Object: add {Get|Set}AutoRemoveKey()

---

CHANGELOG.md
Plugins/Events/NWScript/nwnx_events.nss
Plugins/WebHook/Documentation/README.md
Plugins/WebHook/NWScript/nwnx_webhook.nss
Plugins/WebHook/NWScript/nwnx_webhook_rch.nss
Plugins/WebHook/WebHook.cpp
Plugins/WebHook/WebHook.hpp

Resolves #204 
Examples on new `NWNX_ON_WEBHOOK_FAILURE` usage plus rich messages available in the [README.md](https://github.com/nwnxee/unified/blob/11151f34dc051b323c3d5ba7f7350d6f729cb649/Plugins/WebHook/Documentation/README.md)

WebHook: Add event calls, enhance to support richer messages

---

Plugins/WebHook/WebHook.cpp

Not sure if there are any repercussions with this but it works. @BhaalM can maybe confirm if it stops his crashing and fixes #469

Queue the broadcast message events back to the main queue from the async

---

Plugins/Creature/Creature.cpp

Reflects the new gender to part based models.

Apply gender change to appearance too

---

CHANGELOG.md
Core/NWScript/nwnx_consts.nss
Plugins/Player/NWScript/nwnx_player.nss
Plugins/Player/Player.cpp
Plugins/Player/Player.hpp

A function to override a player's rest animation!

Player: add SetRestAnimation()

---

CHANGELOG.md
Plugins/Util/NWScript/nwnx_util.nss
Plugins/Util/NWScript/nwnx_util_t.nss
Plugins/Util/Util.cpp
Plugins/Util/Util.hpp

Will be required for upcoming Race plugin to efficiently loop through the race and racialmod rows.

Util: Get2DARowCount()

---

CHANGELOG.md
Plugins/Creature/Creature.cpp
Plugins/Creature/Creature.hpp
Plugins/Creature/NWScript/nwnx_creature.nss
Plugins/Creature/NWScript/nwnx_creature_t.nss

Resolves #485
Adds the following functions:
- SetAnimalCompanionCreatureType()
- SetFamiliarCreatureType()
- SetAnimalCompanionName()
- SetFamiliarName()

Creature: add Set{AnimalCompanion|Familiar}CreatureType() & Set{AnimalCompanion|Familiar}Name()

---

CHANGELOG.md
Plugins/Tweaks/CMakeLists.txt
Plugins/Tweaks/Documentation/README.md
Plugins/Tweaks/Tweaks.cpp
Plugins/Tweaks/Tweaks.hpp
Plugins/Tweaks/Tweaks/StringToIntBaseToAuto.cpp
Plugins/Tweaks/Tweaks/StringToIntBaseToAuto.hpp

Will allow for hex strings (prefaced with 0x) to be converted to integers.
Set `NWNX_TWEAKS_STRINGTOINT_BASE_TO_AUTO` to `true`

Tweaks: StringToIntBaseToAuto

---

CHANGELOG.md
Plugins/Object/NWScript/nwnx_object.nss
Plugins/Object/Object.cpp
Plugins/Object/Object.hpp

Object: add {Get|Set}TriggerGeometry()

---

Plugins/Player/NWScript/nwnx_player.nss
Plugins/Player/Player.cpp
Plugins/Player/Player.hpp

Stuff can now have more than one VFX, hurray!

Player: improve ApplyLoopingVisualEffectToObject()

---

CHANGELOG.md
Plugins/Race/NWScript/nwnx_race.nss
Plugins/Race/Race.cpp
Plugins/Race/Race.hpp

Also added `GetParentRace` function. Returns parent race or existing race if no parent.

GetTotalEffectBonus should honor parent race of the target

---

CHANGELOG.md
Core/NWScript/nwnx_consts.nss
Plugins/Util/NWScript/nwnx_util.nss
Plugins/Util/NWScript/nwnx_util_t.nss
Plugins/Util/Util.cpp
Plugins/Util/Util.hpp

Util: GetLastCreatedObject()

---

CHANGELOG.md
Core/NWScript/nwnx_consts.nss
Plugins/Chat/Chat.cpp
Plugins/Chat/Chat.hpp
Plugins/Chat/NWScript/nwnx_chat.nss
Plugins/Chat/NWScript/nwnx_chat_t.nss
Plugins/Race/NWScript/nwnx_race.nss
Plugins/Race/Race.cpp
Plugins/Race/Race.hpp
Plugins/Util/NWScript/nwnx_util.nss
Plugins/Util/NWScript/nwnx_util_t.nss
Plugins/Util/Util.cpp
Plugins/Util/Util.hpp

Resolves #499 - We might want to consider doing the opposite where a PC's voice can carry beyond the hardcoded limit.

Chat: SetChatHearingDistance()

---

Plugins/Events/Events/InventoryEvents.cpp
Plugins/Events/Events/InventoryEvents.hpp
Plugins/Events/Events/ItemEvents.cpp
Plugins/Events/Events/ItemEvents.hpp

Support placeables as well
Include note to change name when moving to 64 bit

Move NWNX_ON_ITEM_INVENTORY_{ADD|REMOVE} to InventoryEvents

---

CHANGELOG.md
Plugins/Events/CMakeLists.txt
Plugins/Events/Events.cpp
Plugins/Events/Events.hpp
Plugins/Events/Events/PVPEvents.cpp
Plugins/Events/Events/PVPEvents.hpp
Plugins/Events/NWScript/nwnx_events.nss

Events: PVP Attitude Change

---

Plugins/Race/Race.cpp

`effNew->m_nNumIntegers=effNew->m_nNumIntegers;` was corrected and some other whitespace/clang tidying up

Race: Fix copying of m_nNumIntegers and some other tidying up

---

CHANGELOG.md
Plugins/Events/Events/InputEvents.cpp
Plugins/Events/Events/InputEvents.hpp
Plugins/Events/NWScript/nwnx_events.nss

Dunno how useful these are for most people, best used with DispatchListMode since these can be called quite a lot.

Events: add AttackObject and ForceMoveToObject events to InputEvents

---

NWNXLib/Plugin.cpp
NWNXLib/Plugin.hpp
NWNXLib/Services/Config/Config.inl
NWNXLib/Services/Events/Events.cpp
NWNXLib/Services/Events/Events.hpp
NWNXLib/Services/Plugins/Plugins.cpp
README.md

These are some relatively minor issues I noticed while familiarizing myself with the codebase.  I'll admit my build/test setup isn't what I want it to be to really contribute yet.  I hope these are helpful.

A handful of minor things.

---

NWNXLib/Services/Commands/Commands.cpp
NWNXLib/Services/PerObjectStorage/PerObjectStorage.cpp
NWNXLib/Services/PerObjectStorage/PerObjectStorage.hpp
Plugins/Administration/Administration.cpp
Plugins/Appearance/Appearance.cpp
Plugins/Area/Area.cpp
Plugins/Creature/Creature.cpp
Plugins/Damage/Damage.cpp
Plugins/Dialog/Dialog.cpp
Plugins/ELC/ELC.cpp
Plugins/Effect/Effect.cpp
Plugins/Encounter/Encounter.cpp
Plugins/Feedback/Feedback.cpp
Plugins/Item/Item.cpp
Plugins/ItemProperty/ItemProperty.cpp
Plugins/Object/Object.cpp
Plugins/Player/Player.cpp
Plugins/Race/Race.cpp
Plugins/Regex/Regex.cpp
Plugins/Reveal/Reveal.cpp
Plugins/SQL/SQL.cpp
Plugins/SkillRanks/SkillRanks.cpp
Plugins/SpellChecker/SpellChecker.cpp
Plugins/Time/Time.cpp
Plugins/Util/Util.cpp
Plugins/Visibility/Visibility.cpp
Plugins/Weapon/Weapon.cpp
Scripts/buildnwnx.sh

Minor and style issues

---

NWNXLib/Services/PerObjectStorage/PerObjectStorage.cpp
NWNXLib/Services/PerObjectStorage/PerObjectStorage.hpp
Plugins/Appearance/Appearance.cpp
Plugins/Appearance/Appearance.hpp

Also fixes a a crash with POS PointerMap cleanup when it was set on a player.

Appearance: Use POS for storage

---

Plugins/MaxLevel/README.md

Make some additions and a correction

Maxlevel README tweak

---

Plugins/Events/NWScript/nwnx_events.nss

Elaborate on which event data is available in map pin events

---

Core/NWNXCore.cpp

Sorry, totally missed the need to deref.

core: Fix area resref logging

---

NWNXLib/API/Constants/ClassType.hpp
NWNXLib/API/Constants/Feat.hpp
NWNXLib/API/Constants/Item.hpp
NWNXLib/API/Constants/RacialType.hpp
NWNXLib/API/Constants/Skill.hpp

Fixes #600
Change a few ToString functions to return "(unknown)" rather than "(invalid)"

nwnxlib/constants: Fix gaps in enums

---

Core/NWNXCore.cpp
NWNXLib/Services/Plugins/Plugins.cpp
NWNXLib/Services/Plugins/Plugins.hpp

Now lazy people can use it too ;D

Core: Update loglevel command to be case insensitive about plugin names

---

Core/NWNXCore.cpp
NWNXLib/API/Constants/Base.hpp
Plugins/MaxLevel/MaxLevel.cpp
Plugins/Object/Object.cpp

Use these in a couple places in my own plugins too so figure it wouldn't hurt to have them as we move forward.

Add ResRefType Constants

---

Plugins/Race/Race.cpp
Plugins/SkillRanks/SkillRanks.cpp
Plugins/Tweaks/Tweaks/SneakAttackCritImmunity.cpp
Plugins/Tweaks/Tweaks/SneakAttackCritImmunity.hpp

Resolves #669 
Haven't found the entries for NWNX_Weapon yet, if they exist

Ruleset.2da Accounting

---

Plugins/Weapon/Weapon.cpp

Weapon: fix a nullptr crash when trying to lookup invalid feat/baseitems

---

Plugins/Chat/Chat.cpp
Plugins/Chat/Chat.hpp
Plugins/Chat/NWScript/nwnx_chat.nss
Plugins/Data/NWScript/nwnx_data.nss
Plugins/Data/Providers/Array.cpp
Plugins/Data/Providers/Array.hpp
Plugins/Events/Events.cpp
Plugins/Events/Events.hpp
Plugins/Events/NWScript/nwnx_events.nss
Plugins/Lua/Lua.cpp
Plugins/Lua/Lua.hpp
Plugins/Lua/NWScript/nwnx_lua.nss
Plugins/Profiler/NWScript/nwnx_profiler.nss
Plugins/Profiler/Profiler.cpp
Plugins/Ruby/NWScript/nwnx_ruby.nss
Plugins/Ruby/Ruby.cpp
Plugins/Ruby/Ruby.hpp
Plugins/WebHook/NWScript/nwnx_webhook.nss
Plugins/WebHook/WebHook.cpp
Plugins/WebHook/WebHook.hpp

Resolves #686 
I think this is the last of them

Plugins: Unify function naming

---

CHANGELOG.md
Plugins/Player/NWScript/nwnx_player.nss
Plugins/Player/Player.cpp
Plugins/Player/Player.hpp

Hopefully this won't be abused. It has legitimate uses.

player: add GetPlatformId()

---

CHANGELOG.md
Core/NWNXCore.cpp
NWNXLib/Services/PerObjectStorage/PerObjectStorage.cpp
NWNXLib/Services/PerObjectStorage/PerObjectStorage.hpp
Plugins/Chat/Chat.cpp
Plugins/Creature/Creature.cpp
Plugins/Damage/Damage.cpp
Plugins/Feedback/Feedback.cpp
Plugins/Player/Player.cpp
Plugins/Reveal/Reveal.cpp
Plugins/SkillRanks/SkillRanks.cpp

Resolves #455 
It is persisted to GFF for all object types. Can maybe even be exposed as `NWNX_Object_SetPersistentXxx()` now.
Not thoroughly tested. Oh well.

Persistent POS

---

NWNXLib/Services/Events/Events.cpp
NWNXLib/Services/Events/Events.hpp
NWNXLib/Services/Events/Events.inl

Few small Events related things.

Events stuff

---

Scripts/Docker/run-server.patch
Scripts/Docker/run-server.sh.new

Docker: only link in settings.tml if it doesn't already exist in the container which can happen due to docker-compose volumes pulling it in

---

CHANGELOG.md
Plugins/Events/CMakeLists.txt
Plugins/Events/Events.cpp
Plugins/Events/Events.hpp
Plugins/Events/Events/ObjectEvents.cpp
Plugins/Events/Events/ObjectEvents.hpp
Plugins/Events/NWScript/nwnx_events.nss

Events: add skippable Lock/Unlock object events

---

README.md

Needs 'Enable Server Widget' toggled in discord settings.

Docs: Show discord badge

---

CHANGELOG.md
Plugins/Creature/Creature.cpp
Plugins/Creature/Creature.hpp
Plugins/Creature/NWScript/nwnx_creature.nss
Plugins/Creature/NWScript/nwnx_creature_t.nss

I reinstalled my OS recently and I haven't set up my testing environment yet so I haven't been able to test the changes. It's an easy fix, I don't see what could be wrong or missing but still I'm tagging it as untested. I hope I will be able to test it tomorrow once I get my server running.
Leaving it here in case someone wants to test/fix it before I get to it.
EDIT: Hopefully fixes #742

Custom class domain/specialization getters and setters

---

CHANGELOG.md
Core/NWNXCore.cpp
Plugins/WebHook/WebHook.cpp

Webhook: fix a crash when trying to send a message in the shutdown script

---

Plugins/ServerLogRedirector/ServerLogRedirector.cpp
Plugins/ServerLogRedirector/ServerLogRedirector.hpp

ServerLogRedirector: fix timestamp trimming

---

CHANGELOG.md
Plugins/Tweaks/Tweaks/SneakAttackCritImmunity.cpp

Fixes #747
Can't test the changes at the moment because I need some sleep. I'll try to set up a testing scenario when I wake up, unless someone wants to give it a go before I do.
PS: Some changes are due to VS's auto-formatting and I only noticed them after pushing the changes. If it breaks consistency I can roll those changes back.

Fix sneak attacks not working on flanked targets

---

CHANGELOG.md
Core/NWNXCore.cpp
Core/README.md

Core: add NWNX_CORE_NWNX_RESOURCE_DIRECTORY_PATH environment variable

---

Dockerfile

Been using this for afew weeks now, seems stable.

Update Dockerfile for dotnet 3.1

---

CHANGELOG.md
Plugins/Optimizations/Optimizations/GameObjectLookup.cpp
Plugins/Optimizations/Optimizations/GameObjectLookup.hpp
Plugins/Util/Util.cpp

Fixes #801  (well, I only tested the nwnx_utils part of it because that was possible from console, but should fix the other one)

optimizations: Fix GOA optimization messing with NWNX functionality

---

CHANGELOG.md
Plugins/SQL/README.md
Plugins/SQL/Targets/MySQL.cpp

SQL: add NWNX_SQL_PORT environment variable

---

CHANGELOG.md
Plugins/Util/NWScript/nwnx_util.nss
Plugins/Util/Util.cpp
Plugins/Util/Util.hpp

Util: add GetScriptReturnValue()

---

Plugins/Administration/Administration.cpp
Plugins/Damage/Damage.cpp
Plugins/SQL/Targets/SQLite.cpp
Plugins/Util/Util.cpp

Fix some compiler warnings

---

CHANGELOG.md
Plugins/Events/Events/InputEvents.cpp
Plugins/Events/Events/InputEvents.hpp
Plugins/Events/NWScript/nwnx_events.nss

Also makes WalkToWaypoint, AttackObject and CastSpell skippable

Events: add CastSpell event to InputEvents

---

CHANGELOG.md
Plugins/Object/NWScript/nwnx_object.nss
Plugins/Object/Object.cpp
Plugins/Object/Object.hpp

Adding this as a workaround so I can change the facing of placeables in an ExecuteScriptChunk call where AssignCommand doesn't work.

Object: add SetFacing()

---

CHANGELOG.md
Plugins/Events/Events/InputEvents.cpp
Plugins/Events/Events/InputEvents.hpp
Plugins/Events/NWScript/nwnx_events.nss

Fiddly to work with, but I'm sure someone, somewhere can find a use for this.
Resolves #787

Events: add KeyboardEvent to InputEvents

---

CHANGELOG.md
Plugins/Player/Player.cpp

Player: fix NWNX_Player_SetPlaceableNameOverride()

---

CHANGELOG.md
Plugins/Events/CMakeLists.txt
Plugins/Events/Events.cpp
Plugins/Events/Events.hpp
Plugins/Events/Events/QuickbarEvents.cpp
Plugins/Events/Events/QuickbarEvents.hpp
Plugins/Events/NWScript/nwnx_events.nss

Events: add QuickbarSetButton event to QuickbarEvents

---

CHANGELOG.md
Plugins/Events/CMakeLists.txt
Plugins/Events/Events.cpp
Plugins/Events/Events.hpp
Plugins/Events/Events/CalendarEvents.cpp
Plugins/Events/Events/CalendarEvents.hpp
Plugins/Events/NWScript/nwnx_events.nss

Adds an event for change in Hour, Day, Month or Year, along with events for Dawn and Dusk.
Thanks to @GoLoT and @mtijanic for help and reviewing this.

Events: Calendar events

---

Plugins/Creature/Creature.cpp

plugins/creature: unsigned char -> uint8_t

---

Plugins/Area/Area.cpp

area: Copy paste error

---

.dockerignore

Avoid copying unnecessary crap to docker image.  I admit a lack of experience with docker, so if this is wrong please advise and I will close PR.

dockerignore: Add lines from gitignore

---

CHANGELOG.md
Plugins/SkillRanks/SkillRanks.cpp
Plugins/SkillRanks/SkillRanks.hpp

SkillRanks: hook LoadRulesetInfo() instead of LoadSkillInfo()

---

Plugins/Util/Util.cpp
Plugins/Weapon/Weapon.cpp

Pr some more minors

---

NWNXLib/Services/Messaging/Messaging.hpp
Plugins/CombatModes/CombatModes.cpp
Plugins/Events/Events.cpp
Plugins/Profiler/Profiler.cpp
Plugins/Profiler/Profiler.hpp
Plugins/SkillRanks/SkillRanks.cpp

It's not used very consistently, so I'm not totally sure this is the  right choice.
https://github.com/nwnxee/unified/blob/6dfc95e23e885df343b556278ed2af40d794c0dd/NWNXLib/Services/Messaging/Messaging.cpp#L45-L58
As it is, it looks like it's making a copy per subscriber?

messaging: Change Handler type to void(const Message&)

---

NWNXLib/Services/Events/Events.cpp

The DotNet plugin actually does something fairly similar to this.

events: Cache the last Event Data lookup

---

Scripts/bootstrap_plugin.sh

I can't imagine anyone not just copying and pasting from an existing plugin, might as well formalize it.  Feedback welcome.
I didn't put any effort into Plugin::Info since Daz mentioned in https://github.com/nwnxee/unified/pull/927 that it's going to be spring cleaned.

scripts: Add bootstrap_plugin.sh

---

CHANGELOG.md
Plugins/Player/NWScript/nwnx_player.nss
Plugins/Player/Player.cpp
Plugins/Player/Player.hpp

Resolves #935
Not super tested, but seems to work ok.

Player: add SetCustomToken()

---

CHANGELOG.md
NWNXLib/API/Constants/Misc.hpp
Plugins/Creature/Creature.cpp
Plugins/Creature/Creature.hpp
Plugins/Creature/NWScript/nwnx_creature.nss
Plugins/Player/Player.cpp

Also fixes some POS related undefined behavior in Player::PossessCreature()

Creature: add AddAssociate()

---

CHANGELOG.md
Plugins/Events/Events/SpellEvents.cpp
Plugins/Events/Events/SpellEvents.hpp
Plugins/Events/NWScript/nwnx_events.nss

Added an event hook in SpellEvents to catch when a spell cast action begins.

Events: Broadcast Spell Cast events

---

CHANGELOG.md
Plugins/ELC/ELC.cpp

ELC: respect CHARGEN_BASE_ABILITY_* ruleset.2da values

---

CHANGELOG.md
Plugins/Events/Events/InputEvents.cpp
Plugins/Events/NWScript/nwnx_events.nss

Resolves #953 
Fun Fact: this also fires for non-dm players pressing the spacebar

Events: add TogglePause event to InputEvents

---

CHANGELOG.md
Plugins/Player/NWScript/nwnx_player.nss
Plugins/Player/Player.cpp
Plugins/Player/Player.hpp

Following short discussion on discord.
Adds a Player function that does what it's name says.

Added Player: SetCreatureNameOverride()

---

Awesome-NWNX.md
README.md

A starter list of NWNX and related projects. Feel free to add to it.
Resolves #574

Add awesome-nwnx list

---

Plugins/Events/NWScript/nwnx_events.nss

@mtijanic in https://github.com/nwnxee/unified/issues/957 you said this was fixed by a PR I made but it wasn't. Now it is though, so your plan worked ;)

documentation correction

---

Plugins/Events/Events/SpellEvents.cpp

Small syntax tweak to match the new format for exclusive hooks

Exclusive hook acquisition syntax change

---

CHANGELOG.md
Plugins/Effect/Effect.cpp
Plugins/Effect/Effect.hpp
Plugins/Effect/NWScript/nwnx_effect.nss
Plugins/Effect/NWScript/nwnx_effect_t.nss

Completely untested at the moment. I'll test before merging..
resolves #963 
I guess a similar thing could be added for IPs, but there's a few ways to do that already.

Add ReplaceEffect()

---

CHANGELOG.md
Core/NWNXCore.cpp
Core/NWNXCore.hpp
Core/README.md

Still have to figure out how to get the custom aliases from Core to my ResourceEvents

Core: add initial support for additional resource directories

---

CHANGELOG.md
Plugins/Events/CMakeLists.txt
Plugins/Events/Events.cpp
Plugins/Events/Events.hpp
Plugins/Events/Events/StoreEvents.cpp
Plugins/Events/Events/StoreEvents.hpp
Plugins/Events/NWScript/nwnx_events.nss

Events: add Request{Buy|Sell} events to StoreEvents

---

CHANGELOG.md
Plugins/Area/Area.cpp
Plugins/Area/Area.hpp
Plugins/Area/NWScript/nwnx_area.nss
Plugins/Player/NWScript/nwnx_player.nss
Plugins/Player/Player.cpp
Plugins/Player/Player.hpp
Plugins/Util/NWScript/nwnx_util.nss
Plugins/Util/Util.cpp
Plugins/Util/Util.hpp

A bunch of cool new things.
Adds the following:
```
NWNX_Player_RemoveEffectFromTURD()
NWNX_Player_SetSpawnLocation()
NWNX_Util_{Get|Set}ResourceOverride()
NWNX_Area_ExportGIT()
```
Resolves #781

Various functions

---

CHANGELOG.md
Plugins/Object/NWScript/nwnx_object.nss
Plugins/Object/NWScript/nwnx_object_t.nss
Plugins/Object/Object.cpp
Plugins/Object/Object.hpp
Plugins/Player/Player.cpp

Also updated `Player:ForcePlaceableInventoryWindow` to force the placeable to have an inventory

Object: SetHasInventory()

---

CHANGELOG.md
Plugins/Administration/Administration.cpp

Obtain the character's first/last name earlier in the function and pass it into the main thread queue for TURD finding

Fix crash in DeletePlayerCharacter()

---

CHANGELOG.md
Plugins/Race/Race.cpp

Discovered this while working on the Feats plugin

Don't remove effects while looping through effects

---

CHANGELOG.md
Plugins/Tweaks/CMakeLists.txt
Plugins/Tweaks/README.md
Plugins/Tweaks/Tweaks.cpp
Plugins/Tweaks/Tweaks.hpp
Plugins/Tweaks/Tweaks/HidePlayersOnCharList.cpp
Plugins/Tweaks/Tweaks/HidePlayersOnCharList.hpp

Allow being able to hide both DMs and PCs or either

Tweak: Change HideDMsOnCharList to HidePlayersOnCharList 

---

CHANGELOG.md
Plugins/Events/Events/ItemEvents.cpp
Plugins/Events/Events/ItemEvents.hpp
Plugins/Events/NWScript/nwnx_events.nss

Events: Acquire Item (Creature Only)

---

CHANGELOG.md
Plugins/Weapon/Weapon.cpp

Weapon: Fix copy/paste error in SetGreaterWeaponFocusFeat()

---

CHANGELOG.md
Plugins/Events/Events/FeatEvents.cpp
Plugins/Events/Events/ObjectEvents.cpp
Plugins/Events/Events/SkillEvents.cpp
Plugins/Events/NWScript/nwnx_events.nss

Resolves #1064 - although not @silent-rock's Edit which doesn't appear to have anything to do with nwnx, but rather nwn itself.

Events: Add ACTION_RESULT in Skill/Feat/Lock events

---

Plugins/Tweaks/Tweaks/PreserveDepletedItems.cpp
Plugins/Tweaks/Tweaks/PreserveDepletedItems.hpp

Fixes #1038 
I can't test it because I haven't updated my testing server to .16 yet. Can someone quickly test it?

Fix exclusive hook conflict

---

CHANGELOG.md
Plugins/Tweaks/CMakeLists.txt
Plugins/Tweaks/README.md
Plugins/Tweaks/Tweaks.cpp
Plugins/Tweaks/Tweaks.hpp
Plugins/Tweaks/Tweaks/FixArmorDexBonusUnderOne.cpp
Plugins/Tweaks/Tweaks/FixArmorDexBonusUnderOne.hpp

Finally. It allows to have armors with a Max DEX bonus of 0.
Closes #1047

Tweaks: Add FixArmorDexBonusUnderOne

---

CHANGELOG.md
Plugins/Tileset/CMakeLists.txt
Plugins/Tileset/NWScript/nwnx_tileset.nss
Plugins/Tileset/README.md
Plugins/Tileset/Tileset.cpp
Plugins/Tileset/Tileset.hpp

A big ol' WIP, no documentation as of yet.

Plugin: Tileset

---

CHANGELOG.md
Plugins/Creature/Creature.cpp
Plugins/Weapon/Weapon.cpp

Additionally:
* added some combat debugging for these feats 
* use ruleset for the Good Aim Feat value
* fix bug in ResolveAttackRoll when checking if combatdebugging was running

Weapon: Fix Greater Weapon feat bonus calculations

---

CHANGELOG.md
CMakeLists.txt
NWNXLib/ScriptVariant.hpp
Plugins/Profiler/Targets/AIMasterUpdates.cpp
Plugins/Profiler/Targets/MainLoop.cpp
Plugins/Profiler/Targets/NetLayer.cpp
Plugins/Profiler/Targets/ObjectAIUpdates.cpp
Plugins/Profiler/Targets/ObjectEventHandlers.cpp
Plugins/Profiler/Targets/Pathing.cpp
Plugins/Profiler/Targets/Scripts.cpp
Scripts/buildnwnx.sh

Also ran `-wpedantic` and cleaned up some unnecessary semi-colons

Build: Only accept RelWithDebInfo as an acceptable CMAKE_BUILD_TYPE

---

CHANGELOG.md
Plugins/Events/CMakeLists.txt
Plugins/Events/Events.cpp
Plugins/Events/Events.hpp
Plugins/Events/Events/JournalEvents.cpp
Plugins/Events/Events/JournalEvents.hpp
Plugins/Events/NWScript/nwnx_events.nss

Events: add Journal Open/Close events to JournalEvents

---

CHANGELOG.md
Plugins/Chat/Chat.cpp

Chat: Targeted messages can be sent on Party and DM channels

---

CHANGELOG.md
Plugins/Events/Events/StealthEvents.cpp
Plugins/Events/Events/StealthEvents.hpp
Plugins/Events/NWScript/nwnx_events.nss

Events: Add skippable SetDetectMode

---

Dockerfile
Dockerfile-gha

This will update both dockerfiles to dotnet 5.0.
Only affect should be supporting more projects.

dotnet 5.0 dockerfile changes

---

CHANGELOG.md
Plugins/SkillRanks/SkillRanks.cpp

fix for calculating the skill bonus from an ability with a negative modifier

very complex and important commit)

---

CHANGELOG.md
Core/README.md
NWNXLib/Encoding.cpp
NWNXLib/Encoding.hpp

Resolves #985 
@Mefi100 could you give this a shot?

add cp1251 locale, rework the definitions a bit

---

Plugins/Feat/Feat.cpp
Plugins/Feat/Feat.hpp
Plugins/Feat/NWScript/nwnx_feat.nss
Plugins/Feat/README.md

Resolves #1149 
Also fixed an issue with bonus feats (from items for example) not applying properly.

Feat: Add Bonus Spell modifier

---

.github/workflows/trivy-analysis.yml

Removed the request for inputs on manual workflow but forgot to fix the specified Dockerfile

CI: Scheduled Trivy Analysis was still broke

---

Plugins/Feat/Feat.cpp
Plugins/Feat/Feat.hpp
Plugins/Feat/NWScript/nwnx_feat.nss
Plugins/Feat/README.md

Also changed lists to sets, cleaner and we're not dealing with much data.

Feat: Add HASTE, SEEINVISIBLE, TRUESEEING, ULTRAVISION and VISUALEFFECT

---

CHANGELOG.md
Plugins/Util/NWScript/nwnx_util.nss
Plugins/Util/Util.cpp
Plugins/Util/Util.hpp

Set module Dusk/Dawn hours

---

CHANGELOG.md
Plugins/Events/Events/ItemEvents.cpp
Plugins/Events/NWScript/nwnx_events.nss

Events: fix nullptr deref crash in the AcquireItem event

---

CHANGELOG.md
Plugins/Administration/Administration.cpp
Plugins/Administration/NWScript/nwnx_admin.nss

Administration: add sKickMessage parameter to DeleteCharacter()

---

.github/workflows/build.yml
.github/workflows/dockerhub-description.yml

Also includes to create/update tagged version image

Docker: Update Docker Hub description when README changes

---

README.md

This was also done to check if the automated dockerhub description update is working.

README updates, small tweaks to docker instructions

---

.github/workflows/dockerhub-description.yml

Also, allow for forks to work too

Docker: For description updates, you need user password not personal access token

---

Scripts/Docker/run-server.patch
Scripts/Docker/run-server.sh.new

Docker: fix module names with spaces

---

Scripts/Docker/run-server.patch
Scripts/Docker/run-server.sh.new

Revert "Docker: fix module names with spaces"

---

CHANGELOG.md
Plugins/Encounter/Encounter.cpp
Plugins/Encounter/Encounter.hpp
Plugins/Encounter/NWScript/nwnx_encounter.nss

It'd be useful to have these for encounters as well as triggers.

Add Get/Set Geometry for encounters

---

CHANGELOG.md
Core/NWScript/nwnx_consts.nss
Plugins/Events/Events/InputEvents.cpp
Plugins/Events/NWScript/nwnx_events.nss

Events: add NWNX_ON_INPUT_EMOTE_* events

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/docker-base.yml
.github/workflows/docker-builder.yml
.github/workflows/dockerhub-description.yml

~Required for PR: https://github.com/nwnxee/unified/pull/1200~
Required to stop everything breaking.

Docker: Pin "ubuntu-latest" to 18.04

---

CHANGELOG.md
Plugins/Area/Area.cpp
Plugins/Area/Area.hpp
Plugins/Area/NWScript/nwnx_area.nss
Plugins/Area/NWScript/nwnx_area_t.nss

GetAmbientSound{Day/Night}

---

NWNXLib/Services/Hooks/Hooks.hpp

Now that the file is over 100 LOC might be a good idea to restore the .cpp, but I'll do that in some cleanup change down the road

hooks: Allow explicit hook ordering

---

NWNXLib/Services/Hooks/Hooks.hpp
Plugins/Creature/Creature.cpp
Plugins/ELC/ELC.cpp
Plugins/MaxLevel/MaxLevel.cpp
Plugins/Race/Race.cpp
Plugins/Race/Race.hpp

Fixes ValidateCharacter hooks for ELC/Race and CanLevelUp for NWNX_CreatureLevelUp/NWNX_MaxLevel

Fix some hooks that might cause trouble due to hook chaining

---

Core/NWNXCore.cpp
Core/NWNXCore.hpp
NWNXLib/Services/PerObjectStorage/PerObjectStorage.cpp
NWNXLib/Services/PerObjectStorage/PerObjectStorage.hpp

Hook order args could use a look, went with Early for the POS ones, wondering if Final is better or not.

Core: update hooks

---

Plugins/Appearance/Appearance.cpp
Plugins/Appearance/Appearance.hpp
Plugins/Chat/Chat.cpp
Plugins/Chat/Chat.hpp
Plugins/CombatModes/CombatModes.cpp
Plugins/Damage/Damage.cpp
Plugins/Damage/Damage.hpp
Plugins/DotNET/DotNET.cpp
Plugins/Effect/Effect.cpp
Plugins/Experimental/Experimentals/AdjustReputationFix.cpp
Plugins/Experimental/Experimentals/DisableLevelUpValidation.cpp
Plugins/Experimental/Experimentals/SuppressPlayerLoginInfo.cpp
Plugins/Experimental/Experimentals/UnhardcodeRangerDualWield.cpp
Plugins/Feedback/Feedback.cpp
Plugins/Lua/Lua.cpp
Plugins/Optimizations/Optimizations/AsyncLogFlush.cpp
Plugins/Optimizations/Optimizations/GameObjectLookup.cpp
Plugins/Player/Player.cpp
Plugins/Reveal/Reveal.cpp
Plugins/ServerLogRedirector/ServerLogRedirector.cpp
Plugins/ServerLogRedirector/ServerLogRedirector.hpp
Plugins/SkillRanks/SkillRanks.cpp
Plugins/SkillRanks/SkillRanks.hpp
Plugins/Tileset/Tileset.cpp
Plugins/Util/Util.cpp
Plugins/Visibility/Visibility.cpp

First batch of updates for #1237

Plugins: update hooks - part 1

---

CHANGELOG.md
Plugins/DotNET/DotNET.cpp
Plugins/DotNET/DotNET.hpp
Plugins/DotNET/DotNETExports.cpp
Plugins/DotNET/NWN/Internal/Bootstrap.cs
Plugins/SWIG/SWIG_DotNET.i
Plugins/SWIG/generate.sh

Merge first: https://github.com/nwnxee/unified/pull/1225

DotNET: Add function hook support, cleanup bootstrap structure

---

NWNXLib/POS.cpp

Wonder which dumdum broke this, hmmm

NWNXLib: fix POS

---

NWNXLib/External/funchook/src/os_func.c
Plugins/Optimizations/GameObjectLookup.cpp

Also remove stupid memcpy() override in funchook :(

Optimizations: Fix up GOA tweaks a bit

---

Plugins/Events/Events/MaterialChangeEvents.cpp

Some big dummy added an else that shouldn't be there

Events: fix MaterialChangeEvent

---

CHANGELOG.md
Plugins/Optimizations/CMakeLists.txt
Plugins/Optimizations/GameObjectLookup.cpp
Plugins/Optimizations/HashTable32.hpp
Plugins/Optimizations/LuoLookup.cpp
Plugins/Optimizations/PlayerLookup.cpp
Plugins/Optimizations/README.md

nwnx_optimizations philosophy: If it's slow, throw RAM at it until it's not.
I'll do a few more of these.

New optimization: LUO lookup

---

Plugins/Optimizations/LuoLookup.cpp

Duh. If there's a XxxMajor, there's probably an XxxMinor too.

optimizations: Fix alternate update message not updating stores

---

Plugins/SWIG/SWIG_DotNET.i

Investigating options for iterating over array pointers (e.g. CNWSArea->m_pTile).

SWIG: Add C Array Wrappers

---

CHANGELOG.md
Plugins/Creature/Creature.cpp
Plugins/Creature/NWScript/nwnx_creature.nss

Add Get{Armor|Shield|Total}CheckPenalty()

---

Plugins/NoStack/README.md

Remove leftover _ characters after find -> replace

Remove extra _ in variable names in README.md

---

CHANGELOG.md
Plugins/Util/NWScript/nwnx_util.nss
Plugins/Util/Util.cpp

In order to be able to turn off ANSI color codes in log writing

Add isatty

---

NWNXLib/Utils.cpp
NWNXLib/nwnx.hpp
Plugins/DotNET/DotNETExports.cpp

Resolves issues with the GetCurrentlyRunningEvent function returning the wrong value. (Thanks @Daztek for finding the fix!)

PushScriptContext: Push scriptEventId to virtual machine stack

---

CHANGELOG.md

OCD trigger prevention

---

Plugins/Creature/Creature.cpp

Creature: remove position asserts from DoItemCastSpell()

---

CHANGELOG.md
NWNXLib/Assert.cpp
NWNXLib/Log.cpp
NWNXLib/Log.hpp
NWNXLib/Platform/Debug.cpp
Plugins/Diagnostics/MemorySanitizer.cpp

- Log to stdout instead of strerr
- Log to nwnx.txt
- Fix memleak

Core: Assert fixes

---

CHANGELOG.md
Plugins/Creature/Creature.cpp
Plugins/Creature/NWScript/nwnx_creature.nss

It may be wanted for fixing known issues with ELC checks.

Adds NWNX_Creature_RemoveFeatByLevel.

---

CHANGELOG.md
Plugins/Rename/Rename.cpp

Rename: fix MessageBus subscription in the wrong place

---

CHANGELOG.md
Plugins/Creature/Creature.cpp
Plugins/Creature/NWScript/nwnx_creature.nss

Again useful for ELC checks for known issues.

Adds NWNX_Creature_SetSkillRankByLevel.

---

CHANGELOG.md
Plugins/Creature/NWScript/nwnx_creature.nss
Plugins/SQL/NWScript/nwnx_sql.nss
Plugins/SQL/SQL.cpp
Plugins/SQL/SQL.hpp
Plugins/SQL/Targets/ITarget.hpp
Plugins/SQL/Targets/MySQL.cpp
Plugins/SQL/Targets/MySQL.hpp
Plugins/SQL/Targets/PostgreSQL.cpp
Plugins/SQL/Targets/PostgreSQL.hpp
Plugins/SQL/Targets/SQLite.cpp
Plugins/SQL/Targets/SQLite.hpp
Plugins/WebHook/External/httplib.h

I added a function to prepare NULL parameters to the SQL. I tested it with MySQL but not with Postgres or SQLite (but it's not difficult change there). If somebody is willing to test it, it would be great.

Adds NWN_SQL_PreparedNULL.

---

Plugins/Compiler/Compiler.cpp

https://discord.com/channels/382306806866771978/382914210176172032/873361770146828338

Workaround for compiler plugin not immediately exiting.

---

Core/NWNXCore.cpp

Still runs non-interactive so any perf boost should still be there.

Don't allow the -quiet flag to close stdout/stderr

---

CHANGELOG.md
Plugins/Optimizations/LuoLookup.cpp
Plugins/Optimizations/README.md

Putting this in Optimizations since it already has all the LUO stuff hooked.
Might decrease perf for clients a little, but I don't play the game so I wouldn't know.

Optimizations: add `NWNX_OPTIMIZATIONS_FIX_PLACEABLE_VFX_REAPPLY_BUG`

---

CHANGELOG.md
Plugins/Events/Events.cpp
Plugins/Events/NWScript/nwnx_events.nss

Really niche, but script chunks can now subscribe to events.

Events: allow script chunks to subscribe to events

---

Plugins/DotNET/DotNETExports.cpp
Plugins/DotNET/NWN/Internal/Bootstrap.cs

Merge first: https://github.com/nwnxee/unified/pull/1466

DotNET: Add raw string stack methods

---

Plugins/Tweaks/FixMulticlassXPPenaltyBug.cpp

Too many class things, imo 
fixes #1482

Tweaks: fix NWNX_TWEAKS_FIX_MULTICLASS_XP_PENALTY_BUG

---

CHANGELOG.md
Plugins/Creature/Creature.cpp
Plugins/Creature/NWScript/nwnx_creature.nss

Creature: add {Get|Set}SkillPointsRemainingByLevel()

---

Plugins/Experimental/CMakeLists.txt
Plugins/Experimental/PlayerHitpointsAsPercentage.cpp

This is about as fun and well-tested as your average reliant robin.
noncommittal noises about fixing #1485

experimental: vague promises of sending percentage-HP to players

---

CHANGELOG.md
Plugins/Creature/Creature.cpp
Plugins/Creature/NWScript/nwnx_creature.nss

Creature: Add GetMovementRateFactorCap function

---

CHANGELOG.md
Plugins/Player/NWScript/nwnx_player.nss
Plugins/Player/Player.cpp

Added three new function to the NWNX_Player plugin.

Added NWNX_Player_{UpdateSkybox, UpdateFogColor, UpdateFogAmount}

---

NWNXLib/API/API/CNWArea.hpp
NWNXLib/API/API/LerpFloat.hpp

API: Update

---

CHANGELOG.md
Plugins/Feat/NWScript/nwnx_feat_2da.nss
Plugins/Feat/README.md

That's already possible with racial modifiers and the race plugin.
Added equivalent functionality for the feat plugin.

Support for loading feat modifiers from a 2da file

---

CHANGELOG.md
Plugins/Creature/Creature.cpp
Plugins/Creature/NWScript/nwnx_creature.nss

No extra stuff. Just 2 pure new functions

Added DecrementRemainingSpellSlots and IncrementRemainingSpellSlots

---

Compatibility/inc_array.nss

No comment.  Straight forward move.

move regexp handling to new built in functions

---

.github/workflows/docker-builder.yml
.github/workflows/dockerhub-description.yml

Disabling the DockerHub readme update action since I can't be bothered fixing it for now

ci: fix some docker things, part 2

---

CHANGELOG.md
Plugins/Creature/Creature.cpp
Plugins/Creature/NWScript/nwnx_creature.nss

Creature: add {Get|Set}MaximumBonusAttacks()

---

NWNXLib/Log.cpp
NWNXLib/Log.hpp

Reverts nwnxee/unified#1627
Breaks ServerLogRedirector apparently.

Revert "Optimize debug logging"

---

CHANGELOG.md
Plugins/Creature/Creature.cpp
Plugins/Creature/NWScript/nwnx_creature.nss

Added "package" argument to NWNX_Creature_LevelUp()

---

CHANGELOG.md
Plugins/Player/NWScript/nwnx_player.nss
Plugins/Player/Player.cpp

Added arguments for passing transform data (scale, translation, rotation) to `NWNX_Player_ShowVisualEffect()` and `NWNX_Player_ApplyInstantVisualEffectToObject()`

Added transform arguments to VFX functions

---

CHANGELOG.md
NWNXLib/API/Constants/MiscRules.hpp
Plugins/Creature/Creature.cpp
Plugins/Creature/NWScript/nwnx_creature.nss
Plugins/ELC/ELC.cpp

Added {Get|Set}AbilityIncreaseByLevel()

---

CHANGELOG.md
Plugins/Experimental/PlayerHitpointsAsPercentage.cpp

Added the new argument nMessageLimit to SendServerToPlayerGameObjUpdate hook

Experimental PlayerHitpointsAsPercentage fix 

---

CHANGELOG.md
Plugins/Object/NWScript/nwnx_object.nss
Plugins/Object/Object.cpp

Per title: Counterparty to GetTrapCreator and also enables the default functionality for the Trap Creator, such as being able to walk over/ignore the trap.

New Function: SetTrapCreator

---

CHANGELOG.md
Plugins/Damage/Damage.cpp

Fixed: NWNX_Damage - damage event did not fire for doors

---

Plugins/Events/NWScript/nwnx_events.nss

Corrected the tag for target object.

Documentation fix for NWN_ON_CREATURE_JUMP_TO_OBJECT

---

Plugins/SQL/NWScript/nwnx_sql.nss

Convenience function to match the other NWNX_SQL_Prepared{Int|Float|...}

add json handling to Prepare calls

---

CHANGELOG.md
Plugins/Item/Item.cpp
Plugins/Item/NWScript/nwnx_item.nss

Lightly tested, no idea how it'll work on an actual server with latency :)

Item: update SetItemAppearance() to also update the item possessor's appearance

---

CHANGELOG.md
Plugins/Events/Events/ObjectEvents.cpp
Plugins/Events/NWScript/nwnx_events.nss

Events: Add events for player XP changes

---

Plugins/HTTPClient/HTTPClient.cpp

Initially struggled with testing, finally realized it is `NWNX_CORE_LOCALE` not `NWNX_LOCALE`

HTTPClient: convert response FromUTF8

---

NWNXLib/Hooks.cpp
NWNXLib/nwnx.hpp

Fix FunctionHook destructor
